/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbo01a3303;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class FrmUAS extends javax.swing.JFrame {

    /**
     * Creates new form FrmUAS
     */
    public FrmUAS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNIP = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        cmbJabatan = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtGP = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtBonus = new javax.swing.JTextField();
        btnBersih = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGaji = new javax.swing.JTable();
        btnBaru = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 0));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(87, 101, 116));
        jLabel1.setText("Data Gaji Karyawan");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("NIP");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Jabatan");

        txtNIP.setEnabled(false);
        txtNIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNIPActionPerformed(evt);
            }
        });
        txtNIP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNIPKeyPressed(evt);
            }
        });

        txtNama.setEnabled(false);
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        cmbJabatan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cmbJabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "DIREKTUR UTAMA", "SUPERVISOR", "ASSISTEN MANAGER", "MANAGER" }));
        cmbJabatan.setEnabled(false);
        cmbJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJabatanActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Gaji Pokok");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("Bonus");

        txtGP.setEditable(false);
        txtGP.setEnabled(false);
        txtGP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGPActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon("F:\\Kuliah\\SMT 4\\PBO2\\utspbo2\\gambar\\Save_16x16.png")); // NOI18N
        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.setHideActionText(true);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtBonus.setEnabled(false);
        txtBonus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBonusActionPerformed(evt);
            }
        });

        btnBersih.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBersih.setIcon(new javax.swing.ImageIcon("F:\\Kuliah\\SMT 4\\PBO2\\utspbo2\\gambar\\Refresh_16x16.png")); // NOI18N
        btnBersih.setText("Bersih");
        btnBersih.setEnabled(false);
        btnBersih.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBersih.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnBersih.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon("F:\\Kuliah\\SMT 4\\PBO2\\utspbo2\\gambar\\Delete_16x16.png")); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setEnabled(false);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon("F:\\Kuliah\\SMT 4\\PBO2\\utspbo2\\gambar\\LogOut_16x16.png")); // NOI18N
        btnExit.setText("Keluar");
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        tblGaji.setBackground(new java.awt.Color(200, 214, 229));
        tblGaji.setForeground(new java.awt.Color(87, 101, 116));
        tblGaji.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIP", "Nama", "Jabatan", "Gaji Bersih", "Potongan", "Gaji Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGaji.setEnabled(false);
        tblGaji.setSelectionForeground(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(tblGaji);
        if (tblGaji.getColumnModel().getColumnCount() > 0) {
            tblGaji.getColumnModel().getColumn(0).setResizable(false);
            tblGaji.getColumnModel().getColumn(1).setResizable(false);
            tblGaji.getColumnModel().getColumn(2).setResizable(false);
            tblGaji.getColumnModel().getColumn(3).setResizable(false);
            tblGaji.getColumnModel().getColumn(4).setResizable(false);
            tblGaji.getColumnModel().getColumn(5).setResizable(false);
        }

        btnBaru.setIcon(new javax.swing.ImageIcon("F:\\Kuliah\\SMT 4\\PBO2\\utspbo2\\gambar\\Add_16x16.png")); // NOI18N
        btnBaru.setText("Baru");
        btnBaru.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBaru.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnBaru.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("F:\\Kuliah\\SMT 4\\PBO2\\utspbo2\\gambar\\LapKonsumen_16x16.png")); // NOI18N
        jButton1.setText("Laporan");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnBaru)
                        .addGap(18, 18, 18)
                        .addComponent(btnExit)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnBersih)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNama)
                                    .addComponent(txtNIP)
                                    .addComponent(cmbJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(150, 150, 150)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBonus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNIP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtGP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtBonus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBersih)
                            .addComponent(btnDelete)
                            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBaru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        btnDelete.setEnabled(true);
        tblGaji.setEnabled(true);
        txtBonus.setEnabled(false);
        txtGP.setEnabled(true);
        txtNama.setEnabled(false);
        cmbJabatan.setEnabled(false);
        double pot;
        int gb, gp, gt, bonus;
        gp = Integer.parseInt(txtGP.getText());
        pot = gp*0.05;
        gb = gp-(int)pot;
        bonus = Integer.parseInt(txtBonus.getText());
        gt =  gb + bonus;
        
        DefaultTableModel dataModel = (DefaultTableModel) tblGaji.getModel();
        List list = new ArrayList<>();
        tblGaji.setAutoCreateColumnsFromModel(true);
        list.add(txtNIP.getText());
        list.add(txtNama.getText());
        list.add(cmbJabatan.getSelectedItem());
        list.add("Rp. "+gb);
        list.add("Rp. "+pot);
        list.add("Rp. "+gt);
        dataModel.addRow(list.toArray());
        
       
        txtBonus.setText("");
        txtGP.setText("");
        txtNIP.setText("");
        txtNIP.requestFocus();
        txtNama.setText("");
        cmbJabatan.setSelectedItem("-- Pilih --");
       
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruActionPerformed
        // TODO add your handling code here:
        txtNIP.setEnabled(true);
        txtNIP.requestFocus();
    }//GEN-LAST:event_btnBaruActionPerformed

    private void txtNIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIPActionPerformed
        txtNama.setEnabled(false);
        txtBonus.setEnabled(true);
        txtBonus.requestFocus();
        btnBersih.setEnabled(true);
        btnDelete.setEnabled(true);
        txtGP.setEnabled(false);
        String nama = null;
        String jabatan = null;
        int gp = 0;
        if(null!=txtNIP.getText())switch (txtNIP.getText()) {
            case "NK001":
                nama = "Basuki";
                jabatan = "DIREKTUR UTAMA";
                gp=15000000;
                break;
            case "NK002":
                nama = "Bambang Purnama";
                jabatan = "SUPERVISOR";
                gp=10000000;
                break;
            case "NK003":
                nama = "Budi Bagus";
                jabatan = "ASSISTEN MANAGER";
                gp=5500000;
                break;
            case "NK004":
                nama = "Mutiara Mita Cahya";
                jabatan = "MANAGER";
                gp=8500000;
                break;
            default:
                break;
        }
        txtNama.setText(String.valueOf(nama));
        cmbJabatan.setSelectedItem(jabatan);
        txtGP.setText(String.valueOf(gp));
    }//GEN-LAST:event_txtNIPActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        
    }//GEN-LAST:event_txtNamaActionPerformed

    private void cmbJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJabatanActionPerformed
        
    }//GEN-LAST:event_cmbJabatanActionPerformed

    private void txtBonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBonusActionPerformed
        btnSave.setEnabled(true);
    }//GEN-LAST:event_txtBonusActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int brs;
        DefaultTableModel dataModel = (DefaultTableModel) tblGaji.getModel();
        brs=tblGaji.getSelectedRow();
        if(brs>=0){
            int opsi=JOptionPane.showConfirmDialog(null, "Yakin Dihapus ?", "Peringatan", JOptionPane.YES_NO_OPTION);
            if (opsi==JOptionPane.YES_OPTION){
                dataModel.removeRow(brs);
            }
        }
        txtNIP.requestFocus();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihActionPerformed
        txtNIP.setText("");
        txtNIP.setEnabled(false);
        txtNama.setText("");
        txtNama.setEnabled(false);
        txtGP.setText("");
        txtGP.setEnabled(false);
        txtBonus.setText("");
        txtBonus.setEnabled(false);
        txtNIP.requestFocus();
        cmbJabatan.setSelectedItem("-- Pilih --");
        cmbJabatan.setEnabled(false);
        btnExit.setEnabled(false);
        btnSave.setEnabled(false);
        btnBersih.setEnabled(false);
    }//GEN-LAST:event_btnBersihActionPerformed

    private void txtGPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGPActionPerformed

    }//GEN-LAST:event_txtGPActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtNIPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNIPKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNIPKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUAS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUAS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnBersih;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbJabatan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblGaji;
    private javax.swing.JTextField txtBonus;
    private javax.swing.JTextField txtGP;
    private javax.swing.JTextField txtNIP;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
